### ISSUE TITLE
Citations and H index wrong in statistics

### ISSUE THREAD

**Issue by davidwozabal** [boz1/tum-scopus-project#13]
Select Breugst, Müller, Sauer, Wozabal and view statistics.

- All except Sauer have non-integer H-indices (e.g., the H-index reported for Wozabal is 9.4, the actual H-index displayed at SCOPUS is 10). H-index are by definition integer values!
- Citation counts are wrong. Citation count for Wozabal in 2019 is shown as 1418 - the actual (current) value displayed at SCOPUS is 328.
- The last column of the displayed table has no label.

**Comment by boz1** [comment]
I think this issue is resolved now.

**Comment by boz1** [comment]
Yearly values are still requiring a fix, but the monthly view is fixed now.
