### ISSUE TITLE
HVB List

### ISSUE THREAD

**Issue by davidwozabal** [boz1/tum-scopus-project#15]
The HVB list is presumably the Handelsblatt list. The weights for this list are not all 1!

Also: When selecting the HVB list the citations and the H-indices change relative to the results when selecting the FT50 list. This should not happen as these two metrics are 'global', i.e., independent of the selected list.

**Comment by nicknn7** [comment]
we will update the weight list accordint to https://www.handelsblatt.com/downloads/9665428/1/journal-ranking.pdf?ticket=ST-65841648-VrCaEkcDMY9gwQRBNCQn-ap5

**Comment by nicknn7** [comment]
the other issue is resolved, see #27
